CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    avatar_url TEXT,
    account_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_account_status
        CHECK (account_status IN ('PENDING_VERIFICATION', 'ACTIVE', 'LOCKED', 'DISABLED')),
    CONSTRAINT chk_users_email_not_blank CHECK (BTRIM(email) <> ''),
    CONSTRAINT chk_users_full_name_not_blank CHECK (BTRIM(full_name) <> '')
);

CREATE UNIQUE INDEX uq_users_email_lower ON users (LOWER(email));
CREATE INDEX idx_users_account_status ON users (account_status);

CREATE TABLE vocabularies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word VARCHAR(100) NOT NULL,
    normalized_word VARCHAR(100) NOT NULL,
    cefr_level VARCHAR(10),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_vocabularies_normalized_word UNIQUE (normalized_word),
    CONSTRAINT chk_vocabularies_cefr_level CHECK (cefr_level IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
    CONSTRAINT chk_vocabularies_word_not_blank CHECK (BTRIM(word) <> ''),
    CONSTRAINT chk_vocabularies_normalized_word_not_blank CHECK (BTRIM(normalized_word) <> '')
);

CREATE INDEX idx_vocabularies_cefr_level ON vocabularies (cefr_level);

CREATE TABLE vocabulary_senses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocabulary_id BIGINT NOT NULL,
    part_of_speech VARCHAR(30) NOT NULL,
    definition_en TEXT,
    meaning_vi TEXT,
    pronunciation VARCHAR(100),
    audio_url TEXT,
    sense_order INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vocabulary_senses_vocabulary
        FOREIGN KEY (vocabulary_id) REFERENCES vocabularies(id) ON DELETE CASCADE,
    CONSTRAINT uq_vocabulary_senses_vocabulary_order UNIQUE (vocabulary_id, sense_order),
    CONSTRAINT chk_vocabulary_senses_order CHECK (sense_order > 0),
    CONSTRAINT chk_vocabulary_senses_part_of_speech_not_blank CHECK (BTRIM(part_of_speech) <> '')
);

CREATE TABLE vocabulary_examples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sense_id BIGINT NOT NULL,
    example_text TEXT NOT NULL,
    translation_vi TEXT,
    example_order INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vocabulary_examples_sense
        FOREIGN KEY (sense_id) REFERENCES vocabulary_senses(id) ON DELETE CASCADE,
    CONSTRAINT uq_vocabulary_examples_sense_order UNIQUE (sense_id, example_order),
    CONSTRAINT chk_vocabulary_examples_order CHECK (example_order > 0),
    CONSTRAINT chk_vocabulary_examples_text_not_blank CHECK (BTRIM(example_text) <> '')
);

CREATE TABLE user_vocabularies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    vocabulary_id BIGINT NOT NULL,
    learning_status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    is_manual_weak BOOLEAN NOT NULL DEFAULT FALSE,
    mastery_score INTEGER NOT NULL DEFAULT 0,
    total_attempts INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    wrong_count INTEGER NOT NULL DEFAULT 0,
    consecutive_wrong INTEGER NOT NULL DEFAULT 0,
    last_reviewed_at TIMESTAMPTZ,
    next_review_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_vocabularies_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_vocabularies_vocabulary
        FOREIGN KEY (vocabulary_id) REFERENCES vocabularies(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_vocabularies_user_vocabulary UNIQUE (user_id, vocabulary_id),
    CONSTRAINT chk_user_vocabularies_learning_status
        CHECK (learning_status IN ('NEW', 'LEARNING', 'WEAK', 'MASTERED')),
    CONSTRAINT chk_user_vocabularies_mastery_score CHECK (mastery_score BETWEEN 0 AND 100),
    CONSTRAINT chk_user_vocabularies_counters_non_negative
        CHECK (total_attempts >= 0 AND correct_count >= 0 AND wrong_count >= 0 AND consecutive_wrong >= 0),
    CONSTRAINT chk_user_vocabularies_answer_counts CHECK (correct_count + wrong_count <= total_attempts)
);

CREATE INDEX idx_user_vocabularies_vocabulary_id ON user_vocabularies (vocabulary_id);
CREATE INDEX idx_user_vocabularies_user_status ON user_vocabularies (user_id, learning_status);
CREATE INDEX idx_user_vocabularies_user_next_review ON user_vocabularies (user_id, next_review_at);
CREATE INDEX idx_user_vocabularies_weak_user ON user_vocabularies (user_id)
    WHERE learning_status = 'WEAK';

CREATE TABLE review_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    total_questions INTEGER NOT NULL DEFAULT 0,
    correct_answers INTEGER NOT NULL DEFAULT 0,
    wrong_answers INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_review_sessions_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_review_sessions_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'ABANDONED')),
    CONSTRAINT chk_review_sessions_counters_non_negative
        CHECK (total_questions >= 0 AND correct_answers >= 0 AND wrong_answers >= 0),
    CONSTRAINT chk_review_sessions_answer_counts CHECK (correct_answers + wrong_answers <= total_questions)
);

CREATE INDEX idx_review_sessions_user_started_at ON review_sessions (user_id, started_at);
CREATE INDEX idx_review_sessions_user_status ON review_sessions (user_id, status);

CREATE TABLE review_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    user_vocabulary_id BIGINT NOT NULL,
    question_type VARCHAR(30) NOT NULL,
    question_content TEXT NOT NULL,
    user_answer TEXT,
    correct_answer TEXT,
    is_correct BOOLEAN NOT NULL,
    response_time_ms INTEGER,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_attempts_session
        FOREIGN KEY (session_id) REFERENCES review_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_attempts_user_vocabulary
        FOREIGN KEY (user_vocabulary_id) REFERENCES user_vocabularies(id) ON DELETE CASCADE,
    CONSTRAINT chk_review_attempts_question_type
        CHECK (question_type IN ('MULTIPLE_CHOICE', 'FILL_BLANK', 'WORD_TO_MEANING', 'MEANING_TO_WORD', 'FLASHCARD')),
    CONSTRAINT chk_review_attempts_response_time CHECK (response_time_ms IS NULL OR response_time_ms >= 0),
    CONSTRAINT chk_review_attempts_question_content_not_blank CHECK (BTRIM(question_content) <> '')
);

CREATE INDEX idx_review_attempts_session_id ON review_attempts (session_id);
CREATE INDEX idx_review_attempts_user_vocabulary_id ON review_attempts (user_vocabulary_id);
CREATE INDEX idx_review_attempts_attempted_at ON review_attempts (attempted_at);
