CREATE TABLE review_session_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    user_vocabulary_id BIGINT NOT NULL,
    item_order INTEGER NOT NULL,
    question_type VARCHAR(30) NOT NULL DEFAULT 'FILL_BLANK',
    question_content TEXT NOT NULL,
    correct_answer TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    answered_at TIMESTAMPTZ,
    CONSTRAINT fk_review_session_items_session
        FOREIGN KEY (session_id) REFERENCES review_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_session_items_user_vocabulary
        FOREIGN KEY (user_vocabulary_id) REFERENCES user_vocabularies(id) ON DELETE CASCADE,
    CONSTRAINT uq_review_session_items_session_order UNIQUE (session_id, item_order),
    CONSTRAINT uq_review_session_items_session_user_vocabulary UNIQUE (session_id, user_vocabulary_id),
    CONSTRAINT chk_review_session_items_order CHECK (item_order > 0),
    CONSTRAINT chk_review_session_items_question_type
        CHECK (question_type IN ('MULTIPLE_CHOICE', 'FILL_BLANK', 'WORD_TO_MEANING', 'MEANING_TO_WORD', 'FLASHCARD')),
    CONSTRAINT chk_review_session_items_status CHECK (status IN ('PENDING', 'ANSWERED', 'SKIPPED')),
    CONSTRAINT chk_review_session_items_question_not_blank CHECK (BTRIM(question_content) <> ''),
    CONSTRAINT chk_review_session_items_answer_not_blank CHECK (BTRIM(correct_answer) <> '')
);

CREATE INDEX idx_review_session_items_session_status ON review_session_items (session_id, status);
CREATE INDEX idx_review_session_items_user_vocabulary ON review_session_items (user_vocabulary_id);

ALTER TABLE review_attempts
    ADD COLUMN session_item_id BIGINT;

ALTER TABLE review_attempts
    ADD CONSTRAINT fk_review_attempts_session_item
    FOREIGN KEY (session_item_id) REFERENCES review_session_items(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX uq_review_attempts_session_item
    ON review_attempts (session_item_id)
    WHERE session_item_id IS NOT NULL;
